"""make household address required

Revision ID: 7361ba982527
Revises: f774d103875f
Create Date: 2026-07-12 15:55:50.287488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7361ba982527'
down_revision: Union[str, Sequence[str], None] = 'f774d103875f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill first: Postgres will reject SET NOT NULL if any existing
    # row still has a NULL address (e.g. households created before the
    # address column existed, or before it became required).
    op.execute("UPDATE households SET address = 'Not provided' WHERE address IS NULL")
    op.alter_column('households', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('households', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
