"""initial schema

Revision ID: bfd1f8065426
Revises: 
Create Date: 2026-07-12 14:05:57.441327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bfd1f8065426'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('households',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('household_name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('number_of_residents', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plastic_code', sa.Integer(), nullable=False),
    sa.Column('quiz_score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('plastic_code >= 1 AND plastic_code <= 7', name='ck_learning_plastic_code_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plastic_code', name='uq_user_plastic_progress')
    )
    op.create_table('reports',
    sa.Column('generated_by_id', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.Enum('csv', 'excel', 'pdf', name='report_type'), nullable=False),
    sa.Column('storage_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_sessions',
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plastic_entries',
    sa.Column('audit_session_id', sa.UUID(), nullable=False),
    sa.Column('room', sa.Enum('kitchen', 'bedroom', 'bathroom', 'living-room', 'garden', 'garage', 'other', name='room_id'), nullable=False),
    sa.Column('item', sa.Enum('bottle', 'bag', 'chair', 'bucket', 'lunch-box', 'toy', 'container', 'pipe', 'other', name='item_category_id'), nullable=False),
    sa.Column('plastic_code', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('identification_method', sa.Enum('known', 'pending-review', name='identification_method'), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(identification_method = 'known' AND plastic_code IS NOT NULL) OR (identification_method = 'pending-review')", name='ck_known_requires_code'),
    sa.CheckConstraint('plastic_code IS NULL OR (plastic_code >= 1 AND plastic_code <= 7)', name='ck_plastic_code_range'),
    sa.ForeignKeyConstraint(['audit_session_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('plastic_entry_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Enum('front', 'back', 'bottom', name='photo_slot'), nullable=False),
    sa.Column('storage_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plastic_entry_id'], ['plastic_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    op.drop_table('plastic_entries')
    op.drop_table('audit_sessions')
    op.drop_table('reports')
    op.drop_table('learning_progress')
    op.drop_table('households')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Alembic's autogenerate does not drop the Postgres ENUM types created
    # for sa.Enum columns above - without this, re-running upgrade() after
    # a downgrade fails with "type already exists".
    bind = op.get_bind()
    postgresql.ENUM(name='photo_slot').drop(bind, checkfirst=True)
    postgresql.ENUM(name='identification_method').drop(bind, checkfirst=True)
    postgresql.ENUM(name='item_category_id').drop(bind, checkfirst=True)
    postgresql.ENUM(name='room_id').drop(bind, checkfirst=True)
    postgresql.ENUM(name='report_type').drop(bind, checkfirst=True)
